AWSTemplateFormatVersion: 2010-09-09
Description: WordPress PHP Lambda
Transform: AWS::Serverless-2016-10-31
Parameters:
  documentRoot:
    Type: String
    Default: /var/task
  directoryIndex:
    Type: String
    Default: index.php

  wpDebug:
    Type: String
    Description: Enables WordPress debug mode
    Default: false
    AllowedValues:
      - true
      - false

  dbHost:
    Description: DB host
    Type: AWS::SSM::Parameter::Value<String>
    Default: /wp/db/host
  dbHostOverride:
    Type: String
    Default: ""
  dbPort:
    Type: Number
    Default: 3306
  dbName:
    Type: AWS::SSM::Parameter::Value<String>
    Description: Usually "/${AWS::StackName}/db/name"
  dbNameOverride:
    Type: String
    Default: ""
  dbUser:
    Type: AWS::SSM::Parameter::Value<String>
    Description: Usually "/${AWS::StackName}/db/user"
  dbUserOverride:
    Type: String
    Default: ""
  dbPass:
    Type: AWS::SSM::Parameter::Value<String>
    Description: Usually "/${AWS::StackName}/db/password"
    NoEcho: true
  dbPassOverride:
    Type: String
    Default: ""
    NoEcho: true

Conditions:
    hasHostOverride: !Not [ !Equals [ !Ref dbHostOverride, "" ] ]
    hasNameOverride: !Not [ !Equals [ !Ref dbNameOverride, "" ] ]
    hasUserOverride: !Not [ !Equals [ !Ref dbUserOverride, "" ] ]
    hasPassOverride: !Not [ !Equals [ !Ref dbPassOverride, "" ] ]

Globals:                     
  Api:
    # https://www.iana.org/assignments/media-types/media-types.xhtml
    # https://github.com/awslabs/serverless-application-model/blob/master/examples/2016-10-31/implicit_api_settings/template.yaml
    BinaryMediaTypes:
      - 'application~1*'
      - 'audio~1*'
      - 'font~1*'
      - 'image~1*'
      - 'message~1*'
      - 'model~1*'
      - 'multipart~1*'
      - 'video~1*'
      - '*~1*'
    MethodSettings:
      - LoggingLevel: INFO
        ResourcePath: /*
        HttpMethod: '*'

Resources:
  function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-wp
      Runtime: nodejs8.10
      CodeUri: out/func-js
      Handler: php-cgi.handler
      MemorySize: 256
      Timeout: 90
      Tracing: Active
      Layers:
        - !Ref wpLayer
        - !Ref phpLayer
      Environment:
        Variables:
          DOC_ROOT: !Ref documentRoot
          DIR_INDEX: !Ref directoryIndex
          WP_DEBUG: !Ref wpDebug
          WP_DATABASE_HOST: !If [ hasHostOverride, !Ref dbHostOverride, !Ref dbHost ]
          WP_DATABASE_PORT: !Ref dbPort
          WP_DATABASE_NAME: !If [ hasNameOverride, !Ref dbNameOverride, !Ref dbName ]
          WP_DATABASE_USER: !If [ hasUserOverride, !Ref dbUserOverride, !Ref dbUser ]
          WP_DATABASE_PASS: !If [ hasPassOverride, !Ref dbPassOverride, !Ref dbPass ]
      Events:
        root:
          Type: Api
          Properties:
            Path: /
            Method: GET
        proxy:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

  phpLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: PHP
      Description: PHP runtime
      ContentUri: out/layer-php/layer-1.d

  wpLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: WordPress
      Description: PHP application
      ContentUri: out/layer-wp

Outputs:
  Endpoint:
    Description: "Endpoint"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"

