AWSTemplateFormatVersion: 2010-09-09
Description: PHP Lambda
Transform: AWS::Serverless-2016-10-31
Resources:
  WordPress:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${AWS::StackName}-wp
      CodeUri: s3://wp.foobar.nz/9bef25bc9c1fc92e243bfe2b1f27bfa5
      Runtime: nodejs8.10
      Handler: index.handler
      MemorySize: 256
      Timeout: 5
      Tracing: Active
      Layers:
      - Ref: LayerPHP
      - Ref: LayerWordPress
      Environment:
        Variables:
          SomeVar: some-var
          SOME_VAR: some var
      Events:
        RootAPI:
          Type: Api
          Properties:
            Path: /
            Method: GET
        API:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
  LayerWordPress:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: WordPress
      Description: WordPress
      ContentUri: s3://wp.foobar.nz/e5f2b1a464b1d85ca4d251a70d41d169
  LayerPHP:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: PHP
      Description: PHP Runtime
      ContentUri: s3://wp.foobar.nz/e8c5d7ae63ae31cc19cb2f1c331ba737
  LayerBootstrap:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: Bootstrap
      Description: Proxies to PHP built-in web server
      ContentUri: s3://wp.foobar.nz/3a3214bb3843d8ee2fb4327f6aa0f4aa
Outputs:
  Endpoint:
    Description: Endpoint
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/
