AWSTemplateFormatVersion: 2010-09-09
Description: PHP Lambda
Transform: AWS::Serverless-2016-10-31
Parameters:
  script:
    Type: String
    Default: wp.php
    AllowedValues:
      - wp.php
      - echo.php
  dbHost:
    Type: String
    Default: localhost:3306
  dbPort:
    Type: String
    Default: 3306
  dbName:
    Type: String
    Default: wordpress
  dbUser:
    Type: String
    Default: wordpress
  dbPass:
    Type: String
    Default: wordpress
Globals:
  Api:
    BinaryMediaTypes: # https://github.com/awslabs/serverless-application-model/blob/master/examples/2016-10-31/implicit_api_settings/template.yaml
      - '*~1*'
    MethodSettings:
      - LoggingLevel: INFO
        ResourcePath: /*
        HttpMethod: '*'
Resources:
  function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-wp
      Runtime: nodejs8.10
      CodeUri: out/func-js
      Handler: php-cgi.handler
      MemorySize: 256
      Timeout: 5
      Tracing: Active
      Layers:
        - !Ref wpLayer
        - !Ref phpLayer
      Environment:
        Variables:
          SCRIPT: !Ref script
          WP_DATABASE_HOST: !Ref dbHost
          WP_DATABASE_PORT: !Ref dbPort
          WP_DATABASE_NAME: !Ref dbName
          WP_DATABASE_USER: !Ref dbUser
          WP_DATABASE_PASSWORD: !Ref dbPass
      Events:
        root:
          Type: Api
          Properties:
            Path: /
            Method: GET
        proxy:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

  phpLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: PHP
      Description: PHP runtime
      ContentUri: out/layer-php/layer-1.d

  wpLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: WordPress
      Description: PHP application
      ContentUri: out/layer-wp

Outputs:
  Endpoint:
    Description: "Endpoint"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"

