AWSTemplateFormatVersion: 2010-09-09
Description: PHP Lambda
Transform: AWS::Serverless-2016-10-31
Parameters:
  documentRoot:
    Type: String
    Default: /var/task
  directoryIndex:
    Type: String
    Default: index.php
  dbHost:
    Type: String
    Default: localhost
  dbPort:
    Type: Integer
    Default: 3306
  dbName:
    Type: String
    Default: wordpress
  dbUser:
    Type: String
    Default: wordpress
  dbPass:
    Type: String
    Default: wordpress
Globals:
  Api:
    # https://www.iana.org/assignments/media-types/media-types.xhtml
    # https://github.com/awslabs/serverless-application-model/blob/master/examples/2016-10-31/implicit_api_settings/template.yaml
    BinaryMediaTypes:
      - 'application~1*'
      - 'audio~1*'
      - 'font~1*'
      - 'image~1*'
      - 'message~1*'
      - 'model~1*'
      - 'multipart~1*'
      - 'video~1*'
      - '*~1*'
    MethodSettings:
      - LoggingLevel: INFO
        ResourcePath: /*
        HttpMethod: '*'
Resources:
  function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-wp
      Runtime: nodejs8.10
      CodeUri: out/func-js
      Handler: php-cgi.handler
      MemorySize: 256
      Timeout: 90
      Tracing: Active
      Layers:
        - !Ref wpLayer
        - !Ref phpLayer
      Environment:
        Variables:
          DOC_ROOT: !Ref documentRoot
          DIR_INDEX: !Ref directoryIndex
          WP_DEBUG: true
          WP_DATABASE_HOST: !Ref dbHost
          WP_DATABASE_PORT: !Ref dbPort
          WP_DATABASE_NAME: !Ref dbName
          WP_DATABASE_USER: !Ref dbUser
          WP_DATABASE_PASS: !Ref dbPass
      Events:
        root:
          Type: Api
          Properties:
            Path: /
            Method: GET
        proxy:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

  phpLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: PHP
      Description: PHP runtime
      ContentUri: out/layer-php/layer-1.d

  wpLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: WordPress
      Description: PHP application
      ContentUri: out/layer-wp

Outputs:
  Endpoint:
    Description: "Endpoint"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"

