AWSTemplateFormatVersion: 2010-09-09
Description: PHP Lambda
Transform: AWS::Serverless-2016-10-31
Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-wp
      Runtime: provided
      CodeUri: out/func-php
      Handler: handler.php
      MemorySize: 256
      Timeout: 5
      Tracing: Active
      Layers:
        - !Ref Layer
      Environment:
        Variables:
          SomeVar: some-var
          SOME_VAR: some var
      Events:
        RootAPI:
          Type: Api
          Properties:
            Path: /
            Method: GET
        API:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

  Layer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: PHP
      Description: PHP Runtime
      ContentUri: out/layer-php/layer-1.d

Outputs:
  Endpoint:
    Description: "Endpoint"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"

