AWSTemplateFormatVersion: 2010-09-09
Description: PHP Lambda
Transform: AWS::Serverless-2016-10-31
Resources:
  WordPress:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-wp
#      Runtime: provided
#      CodeUri: ../out/func-sh
#      Handler: handler.sh:handler

      Runtime: provided
      CodeUri: ../out/func-php
      Handler: debug.php

#      Runtime: nodejs8.10
#      CodeUri: ../out/func-js
#      Handler: index.handler

      MemorySize: 256
      Timeout: 5
      Tracing: Active
      Layers:
        - !Ref LayerPHP
        - !Ref LayerWordPress
        - !Ref LayerBootstrap
      Environment:
        Variables:
          SomeVar: some-var
          SOME_VAR: some var
      Events:
        RootAPI:
          Type: Api
          Properties:
            Path: /
            Method: GET
        API:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

  LayerWordPress:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: WordPress
      Description: WordPress
      ContentUri: ../out/layer-wp

  LayerPHP:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: PHP
      Description: PHP Runtime
      ContentUri: ../out/layer-php

  LayerBootstrap:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: Bootstrap
      Description: Proxies to PHP built-in web server
      ContentUri: ../out/layer-bootstrap

Outputs:
  Endpoint:
    Description: "Endpoint"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"

